### PR TITLE
Implement settings

### PR DESCRIPTION
**Pull request by null-dev**
Settings are generated from a schema. The schema is built from joining together the schema embedded in the frontend and the schema that is fetched from the server.

I've commented out portions of the schema that pertain to unimplemented portions of the frontend.

**NOTE:** You'll need the newest version of the server binary for this to work properly.

### CODE REVIEW

**Comment by Ligerx** [comment]
Awesome work, I'll take a look to check the functionality soon (might be a busy work week).

1) Are you using these VSCode plugins?
> Babel ES6/ES7, ESLint, Debugger for Chrome, Flow Language Support, Prettier

I noticed that the styling is very different from the rrest of the code. If you have ESLint and Prettier, it should become consistent.

2) Too late since you already implemented everything, but I would have implemented the settings without any complicated URL handling (ie. only have /settings).

**Comment by Ligerx** [comment]
Also, I've been using absolute paths (root of the src folder) for imports. Not an issue for this PR, but for the future I prefer them because they're more readable.

**Comment by null-dev** [comment]
@Ligerx You caught me! Actually, I tried using VSCode but it doesn't seem to have an auto-import plugin for flow so I jumped back to Intellij.

That said, I've now managed to replicate most of your config in Intellij except for Prettier. Prettier doesn't work for me in VSCode either actually, it just gives me the following message when I try to format anything:

```
There is no document formatter for 'javascriptreact'-files installed.
```

Do you have any idea what might be causing this? Here is my plugin list: https://nd-images.s3.wasabisys.com/imagebb5f3adcbee56d50.png

I'll reformat the code + redo the imports once I get Prettier working.

**Comment by Ligerx** [comment]
Is that a screenshot of vscode?
Not sure if this helps, but the eslint file sets up the rules such that eslint runs prettier on javascriptreact files (ie. prettier does not run by itself).
https://github.com/Ligerx/TachiWeb-React/blob/master/.eslintrc.json

The project also has vscode specific settings. It associates .js files with javascriptreact so it uses correct syntax highlighting. It also disables prettier on javascriptreact files (because eslint is handling it) but enables prettier for all non-javascriptreact files.
https://github.com/Ligerx/TachiWeb-React/blob/master/.vscode/settings.json

This is a video that I found helpful in setting all this up
https://www.youtube.com/watch?v=bfyI9yl3qfE

**Comment by Ligerx** [comment]
maybe it has something to do with opening the correct workspace/folder in vscode?

**Comment by null-dev** [comment]
@Ligerx Alright, I've spent some more time attempting to replicate your linting config in VSCode to no avail.

I'm starting to notice small discrepancies here and there where the files in your repo do not seem to be linted with the same rules you specified in your `.eslintrc.json`. For example: take a look at the first line in this file: https://github.com/Ligerx/TachiWeb-React/blob/b24f426e1d52886d9a94d33251ee9506cdca0a86/src/index.js#L1 . Notice that `react` is single-quoted. However:

- In the video you mentioned, eslint enforces double quotes instead: https://youtu.be/bfyI9yl3qfE?t=309.
- [In this article](https://blog.echobind.com/integrating-prettier-eslint-airbnb-style-guide-in-vscode-47f07b5d7d6a), with a similar eslint config as yours (Airbnb style + prettier), eslint also enforces double quotes.
- [In another article](https://medium.com/@joshuacrass/javascript-linting-and-formatting-with-eslint-prettier-and-airbnb-30eb746db862) about setting up eslint with Airbnb style + prettier, eslint also enforces double quotes.
- Running eslint via the CLI and passing in your config results in similar results, eslint still enforces the double quotes:
    ```
    $ cd tachiwebui/src/main/js/tachiweb-react && node_modules/eslint/bin/eslint.js -c .eslintrc.json src/index.js 

    /home/nulldev/Documents/Dev/TachiWeb/TW-APIV3/tachiwebui/src/main/js/tachiweb-react/src/index.js
   1:19  error  Replace `'react'` with `"react"`                                                                                                                          prettier/prettier
   2:22  error  Replace `'react-dom'` with `"react-dom"`                                                                                                                  prettier/prettier
   3:46  error  Replace `'redux'` with `"redux"`                                                                                                                          prettier/prettier
   4:26  error  Replace `'react-redux'` with `"react-redux"`                                                                                                              prettier/prettier
   5:19  error  Replace `'redux-thunk'` with `"redux-thunk"`                                                                                                              prettier/prettier
   6:20  error  Replace `'redux-logger'` with `"redux-logger"`                                                                                                            prettier/prettier
   7:37  error  Replace `'redux-devtools-extension'` with `"redux-devtools-extension"`                                                                                    prettier/prettier
   [and more of these kinds of errors...]
    ```

Can you try running: `node_modules/eslint/bin/eslint.js -c .eslintrc.json src/index.js` in the repo root and seeing if there are any errors? Maybe there's some sort of `.prettierrc` or `.prettierignore` file I'm missing.

**Comment by Ligerx** [comment]
Aaaaahhhhhhh my bad I didn't mention some things.
I recently rehauled my eslint/prettier settings, so any files recently touched will be in line with those settings. But a lot of the older project files are using whatever my old linting settings were

**Comment by Ligerx** [comment]
I may re-format all files some time in the future, but as long as new files are consistent, it should be fine.

**Comment by null-dev** [comment]
@Ligerx Alright, hopefully the files match the eslint rules now. Please notify me if you still find more eslint errors.

**Comment by Ligerx** [comment]
Hmmm, I'm running into some issues trying to view your changes locally. Here are the steps I've taken so far:

1. pull your PR branch locally
2. NPM install
3. download the server jar listed on https://github.com/TachiWeb/TachiWeb-Server
4. delete the current /tachiserver-data folder
5. start the server and the front end

image

**Comment by null-dev** [comment]
@Ligerx Whoops, my bad. Had a feature that worked in development but blew up once the server was packaged as a JAR file. Should work now if you re-download the latest server binary.

**Comment by Ligerx** [comment]
Everything seems to be working

**Pull request merged**
